### ISSUE TITLE
Create tabs along the top & remove existing bottom tabs.

### ISSUE THREAD

**Issue by claraparsons** [SmithLabGWSPH/SmithLabGWSPH.github.io#1]
Home
Our Team
Research Projects
Publications
Funders & Partners
Acknowledgements
Join Us

**Comment by kerchner** [comment]
@claraparsons @sasha-baumann:
- I see that the `Code` tab is going away.  Do you think that the `Research Projects` page might be a good home for the PRiSMA info that's currently on https://smithlabgwsph.github.io/code/ ?
- Should the Funding info that's currently towards the bottom of the main page move to become the content of the new `Funders & Partners` page?
- What's the content for `Acknowledgments` (which btw is the preferred American spelling)?

**Comment by claraparsons** [comment]
@sasha-baumann deleted the code portion from our website copy- Sasha, do you want to just take the PRISMA code info off? Or rehome?

**Comment by claraparsons** [comment]
Create funders & partners tab, I can add relevant text we have decided on! Same with Acknowledgments!

**Comment by claraparsons** [comment]
We can also create a 'join us' tab; i can add the job sections/descriptions to that, too.

**Comment by sasha-baumann** [comment]
@claraparsons As per the website copy, the information about the code was relocated under the Acknowledgements tab. @kerchner Confirming that the Code tab can be deleted; Acknowledgements and Funders & Partners are the new tabs for the information you've mentioned. Thanks!
