### ISSUE TITLE
Organize publications by year

### ISSUE THREAD

**Issue by claraparsons** [SmithLabGWSPH/SmithLabGWSPH.github.io#10]
@kerchner we can work on together after I've updated the site will all publications to have. @sasha-baumann - did we want some featured in specific? or just list?

**Comment by kerchner** [comment]
@claraparsons Yes, we can try to find some examples to model this after.  Perhaps start with something super simple like just a list with headers for each year, and some "anchor links" at the top to help jump down to a specific year.  Then we can get fancier after that.

The ultra basic one might look like this:

(maybe some year links here to jump?)

## 2023

Publication 1    
Publication 2  

## 2022

Publication 3  
Publication 4
...

**Comment by claraparsons** [comment]
Yes, really like that! @sasha-baumann - you too?

**Comment by sasha-baumann** [comment]
Confirming this looks great! Suggesting that each publication be listed as a complete citation or an abbreviated one (e.g., Authors, year, DOI, link). Open to keeping it simple beyond organizing by year. Thanks @kerchner

**Comment by kerchner** [comment]
@claraparsons @sasha-baumann I have a prototype of this working in the `t10-pubs-by-year` branch.  It functions as desired, but it could benefit from being more compact:
![image](https://user-images.githubusercontent.com/3451175/228925245-19669429-866b-4729-8c4a-9103f3ffd9a4.png)

Let me know if you'd like to meet to discuss.  And/or, I will also work on improving the documentation around [how to test a code branch](https://github.com/SmithLabGWSPH/SmithLabGWSPH.github.io/wiki/Testing-a-code-branch-----Git-workflow)

**Comment by claraparsons** [comment]
I really like this, personally. Sasha and I were saying today that we'll
flesh out the website copy we've made a bit more to finish up the study
blurbs we're missing & clarify which publications should be displayed.
Sasha- do you think maybe based on this we could do the msot cited from
each year? Or still just most cited of all time?
