### ISSUE TITLE
Access payment method 

### ISSUE THREAD

**Issue by 1answer4all** [SmithLabGWSPH/SmithLabGWSPH.github.io#12]
chatr info for 2046476412: Your current account balance is $0.00, and it's not enough to cover your monthly service fee of $45.00 due today. Simply top up your account to stay connected. Did you know you may be eligible to enroll in Day Pass? For a low daily fee of $3.00, keep using your phone until 2023-03-29. 
All you need is a minimum balance of $3.00 then reply ENROLL to this message to get started today! 
For more information on Day Pass, check out www.chatrmobile.com/daypass 
Reply DPSTOP to stop receiving these reminder messages.

**Comment by kerchner** [comment]
@claraparsons I have reported and blocked this "phishing" Github account so the account will no longer be able to make any pots.
