### ISSUE TITLE
Remove the "Home" link

### ISSUE THREAD

**Issue by kerchner** [SmithLabGWSPH/SmithLabGWSPH.github.io#3]
Because the 
![image](https://user-images.githubusercontent.com/3451175/221015711-e6fc065d-1b8e-48c2-bf8a-e8340711d792.png)
link in the upper left corner does the same thing.

@claraparsons @sasha-baumann , your thoughts?

**Comment by claraparsons** [comment]
Good with me.

**Comment by sasha-baumann** [comment]
@kerchner Confirming this sounds good. Possible to change the text as well from Smith Lab @ GWSPH to Smith Lab | GW School of Public Health?
