### ISSUE TITLE
Add logos to studies

### ISSUE THREAD

**Issue by claraparsons** [SmithLabGWSPH/SmithLabGWSPH.github.io#8]
Next to the study description, it would be nice to have the logo next to the text!
![Main Logo - PRISMA - Circle with Badges](https://user-images.githubusercontent.com/110127526/221233479-c9f1ae7f-a3a5-422c-abc1-29486aba24cd.png)

**Comment by kerchner** [comment]
The code for the research page actually is trying to retrieve images from https://github.com/SmithLabGWSPH/SmithLabGWSPH.github.io/tree/master/images/respic but they are all missing except for the Covid101 image.   You can see the names of the missing image files when you look in the research page code here:  https://raw.githubusercontent.com/SmithLabGWSPH/SmithLabGWSPH.github.io/master/_pages/research.md

We could (as a future, separate issue) make this page easier to maintain by making it more like how the publications page works, where you maintain it by adding to a .yml file: https://github.com/SmithLabGWSPH/SmithLabGWSPH.github.io/blob/master/_data/publist.yml
